"""Narrative builder subagent for GTM document generation."""

from gtm_agent.prompts import NARRATIVE_SUBAGENT_PROMPT
from gtm_agent.tools.artifacts import write_artifact

# Narrative builder subagent configuration
narrative_subagent = {
    "name": "narrative-builder",
    "description": (
        "Builds strategic GTM narrative from diagnostic context. "
        "Creates positioning statement, value proposition, and ICP definition."
    ),
    "system_prompt": NARRATIVE_SUBAGENT_PROMPT,
    "tools": [write_artifact],
    "model": "anthropic:claude-sonnet-4-20250514",
}


def build_narrative_context(
    company_name: str,
    product_description: str,
    icp_answer: str,
    problem_answer: str,
    validation_answer: str,
    scorecard: dict,
) -> dict:
    """Build context dict for narrative subagent.

    Args:
        company_name: Name of the company
        product_description: Description of the product/service
        icp_answer: User's answer to ICP question
        problem_answer: User's answer to problem clarity question
        validation_answer: User's answer to validation status question
        scorecard: The GTM Escalator scorecard dict

    Returns:
        Context dict to pass to narrative subagent
    """
    return {
        "company_name": company_name,
        "product_description": product_description,
        "icp_answer": icp_answer,
        "problem_answer": problem_answer,
        "validation_answer": validation_answer,
        "scorecard": scorecard,
        "current_level": scorecard.get("level", 1),
        "gaps": scorecard.get("gaps", []),
    }


NARRATIVE_TEMPLATE = """# GTM Narrative: {company_name}

## Positioning Statement

{positioning_statement}

## Value Proposition

**Problem**: {problem_statement}

**Solution**: {solution_summary}

**Benefit**: {key_benefit}

## Ideal Customer Profile (ICP)

### Demographics
{demographics}

### Psychographics
{psychographics}

### Trigger Events
{trigger_events}

---

*Generated by GTM Deep Agent based on Level {level} diagnostic assessment*
"""
