"""Voice cloner subagent for generating voice-matched content."""

from gtm_agent.prompts import VOICE_CLONER_SUBAGENT_PROMPT
from gtm_agent.tools.artifacts import write_artifact

# Voice cloner subagent configuration
voice_cloner_subagent = {
    "name": "voice-cloner",
    "description": (
        "Analyzes writing samples to clone founder's voice. "
        "Generates voice-matched email sequences and LinkedIn posts."
    ),
    "system_prompt": VOICE_CLONER_SUBAGENT_PROMPT,
    "tools": [write_artifact],
    "model": "anthropic:claude-sonnet-4-20250514",
}


def build_voice_context(
    narrative: str,
    company_name: str,
    icp: str,
    writing_samples: list[str] | None = None,
) -> dict:
    """Build context dict for voice cloner subagent.

    Args:
        narrative: The full narrative document
        company_name: Name of the company
        icp: Ideal customer profile description
        writing_samples: Optional list of writing samples from founder

    Returns:
        Context dict to pass to voice cloner subagent
    """
    return {
        "narrative": narrative,
        "company_name": company_name,
        "icp": icp,
        "writing_samples": writing_samples or [],
        "has_samples": bool(writing_samples),
    }


def analyze_voice_profile(writing_samples: list[str]) -> dict:
    """Analyze writing samples to extract voice profile.

    This is a helper function that extracts voice characteristics
    from writing samples. In production, the LLM does this analysis.

    Args:
        writing_samples: List of writing samples

    Returns:
        Voice profile dict
    """
    if not writing_samples:
        return {
            "tone": "professional",
            "vocabulary_level": "moderate",
            "sentence_length": "medium",
            "personality_markers": ["direct", "clear", "confident"],
        }

    # Calculate basic metrics from samples
    all_text = " ".join(writing_samples)
    words = all_text.split()
    sentences = all_text.split(".")

    avg_sentence_length = len(words) / max(len(sentences), 1)

    # Determine characteristics based on metrics
    sentence_length = (
        "short" if avg_sentence_length < 10 else "medium" if avg_sentence_length < 20 else "long"
    )

    # Check for complexity markers
    complex_words = ["therefore", "consequently", "furthermore", "notwithstanding"]
    has_complex = any(w.lower() in all_text.lower() for w in complex_words)
    vocabulary_level = "complex" if has_complex else "moderate"

    # Check for conversational markers
    conversational_markers = ["hey", "btw", "gonna", "wanna", "kinda"]
    is_conversational = any(m in all_text.lower() for m in conversational_markers)
    tone = "conversational" if is_conversational else "professional"

    return {
        "tone": tone,
        "vocabulary_level": vocabulary_level,
        "sentence_length": sentence_length,
        "personality_markers": ["analytical", "direct"],
    }


EMAIL_SEQUENCE_TEMPLATE = """# Cold Email Sequence

## Email 1: Problem Awareness

**Subject**: {subject_1}

{body_1}

---

## Email 2: Solution Introduction

**Subject**: {subject_2}

{body_2}

---

## Email 3: Call to Action

**Subject**: {subject_3}

{body_3}

---

*Voice Profile: {tone} tone, {vocabulary_level} vocabulary*
*Generated by GTM Deep Agent Voice Cloner*
"""


LINKEDIN_POSTS_TEMPLATE = """# LinkedIn Posts

## Post 1: Problem Awareness

{post_1}

---

## Post 2: Solution/Value

{post_2}

---

## Post 3: Social Proof/CTA

{post_3}

---

*Optimized for {icp} audience*
*Generated by GTM Deep Agent Voice Cloner*
"""
